name: Update Submodules and Create PR

on:
  schedule:
    - cron: "0 17 * * *" # Runs daily at 5 PM UTC (17:00)
  workflow_dispatch: # Allows manual triggering

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize and Update Submodules
        run: |
          git submodule init
          git submodule update --recursive --remote
          git submodule foreach git switch develop

      - name: Check for Changes
        id: check-changes
        run: |
          git status --porcelain
          if [ -z "$(git status --porcelain)" ]; then
            echo "::set-output name=changed::false"
          else
            echo "::set-output name=changed::true"
          fi

      - name: Create Pull Request
        if: steps.check-changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update submodules"
          title: "Update Submodules"
          body: "This pull request updates all submodules to their latest versions."
          branch: update-submodules
          base: main
